concurrency: 1
continue_on_failure: true
virtual_environment:
  keep_virtual_environment: false
  requirements: []
automations:
  food_sow_dbt_test:
    command: dbt_test
    automation_config:
      target_projects:
        - "pillars"
    throw_exception: true
    test_args:
      - "--select=tag:food_sow"
      - "--target=dev"
  engagement_dbt_test:
    command: dbt_test
    automation_config:
      target_projects:
        - "pillars"
    throw_exception: true
    test_args:
      - "--select=tag:egmt_shop_online"
