concurrency: 1
continue_on_failure: false
automations:
  general_dbt_test:
    command: dbt_test
    automation_config:
      build_before_test: true
      target_projects:
        - "default/offer_attachment_customizable"
      dbt_variable:
        var_1: value_1
      dbt_dependency:
        - package: dbt-labs/dbt_utils
          version: 1.3.0
    throw_exception: true
    automation_args:
