-   id: github-write-protection-pr
    name: Check write-protection files changed in a Github pull request.
    description: |
      This hook is used to check any files under write-protection are changed
      in a Github pull request. 
      It requires the following environmental variables:
        1. ENV_GITHUB_SOURCE_REF: The head reference of this PR
        2. ENV_GITHUB_TARGET_REF: The merge reference of this PR
        3. ENV_GITHUB_SOURCE_REF: The Github ID of users who authors changes
      It accepts following command line option:
        1. `-k` directly followed by a semi-colon separated Github IDs as admins
           For changes authored by any users in this ID list, the check is skipped.
      SYNOPSIS:
        <this_pre_commit_script> -kuser1;user2;user3 <candidate files to be checked>
    entry: scripts/write-protection-pr.sh
    language: system
    files: "^$"