# action.yml
name: 'Run configured integration test cases'
description: 'An action run tests declared from configuration file'
inputs:
  automation-config-file:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - integration-test
    - "--automation-config-file"
    - ${{ inputs.automation-config-file }}
