# action.yml
name: 'PR Write Protection Check'
description: 'Check write-protection intact in the pull request'
inputs:
  test-config-file:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - integration-test
    - "-test-config-file"
    - ${{ inputs.test-config-file }}
