on: [push]

jobs:
  publish_assets:
    runs-on: ubuntu-latest
    name: A job to build wheel package and publish it to release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Poetry Build
        run: |
          pipx install poetry
          poetry build
          ls dist/
      - name: Check project version with release version
        run: |
          project_version=$(poetry version -s)
          echo ${project_version} ${GITHUB_RELEASE_TAG}
          [[ ${GITHUB_RELEASE_TAG#v} == ${project_version} ]] || exit 1
        env:
          GITHUB_RELEASE_TAG: v1.0.0